# Generated by Django 6.0.1 on 2026-02-02 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomina', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'TBL_Usuario',
            },
        ),
        migrations.CreateModel(
            name='TBL_Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_video', models.CharField(max_length=50)),
                ('extension', models.CharField(max_length=5)),
                ('tamano', models.IntegerField()),
            ],
            options={
                'db_table': 'TBL_Video',
            },
        ),
        migrations.CreateModel(
            name='TBL_UsuarioVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos_app.tbl_usuario')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos_app.tbl_video')),
            ],
            options={
                'db_table': 'TBL_UsuarioVideo',
                'unique_together': {('usuario', 'video')},
            },
        ),
    ]
